# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ImBee/Repositories/Git/ImBee/Bitmaps/ShenanigansWithBitmaps

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ImBee/Repositories/Git/ImBee/Bitmaps/ShenanigansWithBitmaps

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ImBee/Repositories/Git/ImBee/Bitmaps/ShenanigansWithBitmaps/CMakeFiles /home/ImBee/Repositories/Git/ImBee/Bitmaps/ShenanigansWithBitmaps//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ImBee/Repositories/Git/ImBee/Bitmaps/ShenanigansWithBitmaps/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SWB

# Build rule for target.
SWB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SWB
.PHONY : SWB

# fast build rule for target.
SWB/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/build
.PHONY : SWB/fast

ShenanigansWithBitmaps/Source/Core/Application.o: ShenanigansWithBitmaps/Source/Core/Application.cpp.o
.PHONY : ShenanigansWithBitmaps/Source/Core/Application.o

# target to build an object file
ShenanigansWithBitmaps/Source/Core/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/ShenanigansWithBitmaps/Source/Core/Application.cpp.o
.PHONY : ShenanigansWithBitmaps/Source/Core/Application.cpp.o

ShenanigansWithBitmaps/Source/Core/Application.i: ShenanigansWithBitmaps/Source/Core/Application.cpp.i
.PHONY : ShenanigansWithBitmaps/Source/Core/Application.i

# target to preprocess a source file
ShenanigansWithBitmaps/Source/Core/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/ShenanigansWithBitmaps/Source/Core/Application.cpp.i
.PHONY : ShenanigansWithBitmaps/Source/Core/Application.cpp.i

ShenanigansWithBitmaps/Source/Core/Application.s: ShenanigansWithBitmaps/Source/Core/Application.cpp.s
.PHONY : ShenanigansWithBitmaps/Source/Core/Application.s

# target to generate assembly for a file
ShenanigansWithBitmaps/Source/Core/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/ShenanigansWithBitmaps/Source/Core/Application.cpp.s
.PHONY : ShenanigansWithBitmaps/Source/Core/Application.cpp.s

ShenanigansWithBitmaps/Source/Core/Bitmap.o: ShenanigansWithBitmaps/Source/Core/Bitmap.cpp.o
.PHONY : ShenanigansWithBitmaps/Source/Core/Bitmap.o

# target to build an object file
ShenanigansWithBitmaps/Source/Core/Bitmap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/ShenanigansWithBitmaps/Source/Core/Bitmap.cpp.o
.PHONY : ShenanigansWithBitmaps/Source/Core/Bitmap.cpp.o

ShenanigansWithBitmaps/Source/Core/Bitmap.i: ShenanigansWithBitmaps/Source/Core/Bitmap.cpp.i
.PHONY : ShenanigansWithBitmaps/Source/Core/Bitmap.i

# target to preprocess a source file
ShenanigansWithBitmaps/Source/Core/Bitmap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/ShenanigansWithBitmaps/Source/Core/Bitmap.cpp.i
.PHONY : ShenanigansWithBitmaps/Source/Core/Bitmap.cpp.i

ShenanigansWithBitmaps/Source/Core/Bitmap.s: ShenanigansWithBitmaps/Source/Core/Bitmap.cpp.s
.PHONY : ShenanigansWithBitmaps/Source/Core/Bitmap.s

# target to generate assembly for a file
ShenanigansWithBitmaps/Source/Core/Bitmap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/ShenanigansWithBitmaps/Source/Core/Bitmap.cpp.s
.PHONY : ShenanigansWithBitmaps/Source/Core/Bitmap.cpp.s

ShenanigansWithBitmaps/Source/Core/HexEditor.o: ShenanigansWithBitmaps/Source/Core/HexEditor.cpp.o
.PHONY : ShenanigansWithBitmaps/Source/Core/HexEditor.o

# target to build an object file
ShenanigansWithBitmaps/Source/Core/HexEditor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/ShenanigansWithBitmaps/Source/Core/HexEditor.cpp.o
.PHONY : ShenanigansWithBitmaps/Source/Core/HexEditor.cpp.o

ShenanigansWithBitmaps/Source/Core/HexEditor.i: ShenanigansWithBitmaps/Source/Core/HexEditor.cpp.i
.PHONY : ShenanigansWithBitmaps/Source/Core/HexEditor.i

# target to preprocess a source file
ShenanigansWithBitmaps/Source/Core/HexEditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/ShenanigansWithBitmaps/Source/Core/HexEditor.cpp.i
.PHONY : ShenanigansWithBitmaps/Source/Core/HexEditor.cpp.i

ShenanigansWithBitmaps/Source/Core/HexEditor.s: ShenanigansWithBitmaps/Source/Core/HexEditor.cpp.s
.PHONY : ShenanigansWithBitmaps/Source/Core/HexEditor.s

# target to generate assembly for a file
ShenanigansWithBitmaps/Source/Core/HexEditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/ShenanigansWithBitmaps/Source/Core/HexEditor.cpp.s
.PHONY : ShenanigansWithBitmaps/Source/Core/HexEditor.cpp.s

ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.o: ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.cpp.o
.PHONY : ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.o

# target to build an object file
ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.cpp.o
.PHONY : ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.cpp.o

ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.i: ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.cpp.i
.PHONY : ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.i

# target to preprocess a source file
ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.cpp.i
.PHONY : ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.cpp.i

ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.s: ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.cpp.s
.PHONY : ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.s

# target to generate assembly for a file
ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.cpp.s
.PHONY : ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.cpp.s

# target to build an object file
cmake_pch.hxx.gch:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/cmake_pch.hxx.gch
.PHONY : cmake_pch.hxx.gch

# target to preprocess a source file
cmake_pch.hxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/cmake_pch.hxx.i
.PHONY : cmake_pch.hxx.i

# target to generate assembly for a file
cmake_pch.hxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SWB.dir/build.make CMakeFiles/SWB.dir/cmake_pch.hxx.s
.PHONY : cmake_pch.hxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SWB"
	@echo "... ShenanigansWithBitmaps/Source/Core/Application.o"
	@echo "... ShenanigansWithBitmaps/Source/Core/Application.i"
	@echo "... ShenanigansWithBitmaps/Source/Core/Application.s"
	@echo "... ShenanigansWithBitmaps/Source/Core/Bitmap.o"
	@echo "... ShenanigansWithBitmaps/Source/Core/Bitmap.i"
	@echo "... ShenanigansWithBitmaps/Source/Core/Bitmap.s"
	@echo "... ShenanigansWithBitmaps/Source/Core/HexEditor.o"
	@echo "... ShenanigansWithBitmaps/Source/Core/HexEditor.i"
	@echo "... ShenanigansWithBitmaps/Source/Core/HexEditor.s"
	@echo "... ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.o"
	@echo "... ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.i"
	@echo "... ShenanigansWithBitmaps/Source/EntryPoint/Win32/Entry.s"
	@echo "... cmake_pch.hxx.gch"
	@echo "... cmake_pch.hxx.i"
	@echo "... cmake_pch.hxx.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

